name: Build Docker Image

on:
  push:

jobs:
  build-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./src/WC.Service.Registration.API/Dockerfile
          push: false
          tags: test/app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
