name: Build and Publish Docker Image

on:
  pull_request:
    types:
      - closed

jobs:
  build-and-push:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./src/WC.Service.Registration.API/Dockerfile
          push: true
          tags: saintefim/wc-service-registration:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
